name: work_options
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  dio: ^4.0.6
  email_validator: ^2.0.1
  flutter:
    sdk: flutter
  flutter_pw_validator: ^1.4.2
  flutter_secure_storage: ^5.0.2
  flutter_svg: ^1.0.3
  http: ^0.13.4
  image_picker: ^0.8.5
  path_provider: ^2.0.11
  wc_form_validators: ^1.0.0

dev_dependencies:
  flutter_lints: ^1.0.0
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/icons/current_job_file.png
    - assets/images/splash.png
    - assets/icons/user_profile.svg
    - assets/images/register.png
    - assets/images/dashboard.png
    - assets/images/user_ask.jpg
    - assets/images/add_job.png

  fonts:
    - family: Bell MT
      fonts:
        - asset: assets/fonts/Bell MT.ttf
